# Generated by Django 2.0.5 on 2018-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180528_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pending_input',
            field=models.BooleanField(default=False),
        ),
    ]
