# Generated by Django 2.0.5 on 2018-05-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_person_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bonus_currency',
            field=models.CharField(default='ETH', max_length=50),
        ),
    ]
