# Generated by Django 2.0.5 on 2018-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gc_invite',
            field=models.TextField(blank=True, null=True, verbose_name='Message to display when inviting user to group channel'),
        ),
        migrations.AddField(
            model_name='setting',
            name='gcid',
            field=models.CharField(default='', max_length=50, verbose_name='Telegram Group Channel ID'),
        ),
        migrations.AddField(
            model_name='setting',
            name='max_referral_message',
            field=models.TextField(blank=True, null=True, verbose_name='Message to display when user reaches max number of referrals'),
        ),
    ]
