# Generated by Django 2.0.5 on 2018-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180531_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='channel_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
