# Generated by Django 2.0.5 on 2018-05-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20180531_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='invest_info',
            field=models.TextField(default='default', verbose_name='Information on how users can invest in ICO'),
        ),
    ]
