# Generated by Django 2.0.5 on 2018-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_setting_invest_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='menu_text',
            field=models.TextField(blank=True, null=True, verbose_name='Message to display whenever the Menu keyboard is sent to user.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='api_key',
            field=models.CharField(max_length=100, verbose_name='API Key'),
        ),
    ]
